import Vue from 'vue'
import { Button, Form, FormItem, Avatar, Input, Select, Option, Scrollbar, Collapse, CollapseItem, Message, Container, Header, Aside, Main, Menu, Submenu, MenuItemGroup, MenuItem, Row, Col, Card, Tabs, TabPane, Radio, RadioGroup, Slider, Switch, Badge } from 'element-ui'

Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Avatar)
Vue.use(Input)
Vue.use(Select)
Vue.use(Option)
Vue.use(Scrollbar)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(Row)
Vue.use(Col)
Vue.use(Card)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(Slider)
Vue.use(Switch)
Vue.use(Badge)

Vue.prototype.$message = Message
